// Copyright 2024 JetBrains s.r.o. and contributors.
// Use of this source code is governed by the Apache 2.0 license.

package com.github.mkartashev.hserr.language

import com.github.mkartashev.hserr.HsErrIcons
import com.intellij.openapi.fileTypes.LanguageFileType
import javax.swing.Icon

object HsErrFileType : LanguageFileType(HsErrLanguage) {
    override fun getName() = "HsErr"

    override fun getDescription() = "HotSpot Fatal Error Log generated by the JVM when it crashes"

    override fun getDefaultExtension() = "log"

    override fun getIcon(): Icon = HsErrIcons.FILE
}
